# Generated by Django 5.1.2 on 2024-11-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=12)),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_number', models.TextField()),
                ('street_name', models.TextField()),
                ('apt_number', models.TextField()),
                ('zip_code', models.TextField()),
                ('birthdate', models.DateField()),
                ('reg_date', models.DateField()),
                ('party', models.TextField()),
                ('precinct', models.PositiveIntegerField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
            ],
        ),
    ]
