# Generated by Django 5.1.3 on 2024-11-16 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLUB_NAME', models.CharField(max_length=100)),
                ('LEADER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOCATION', models.CharField(max_length=300)),
                ('DATE', models.DateTimeField()),
                ('MAT_COUNT', models.IntegerField()),
                ('MATCHES_PER_COMPETITOR', models.IntegerField()),
                ('HOST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.club')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULL_NAME', models.CharField(max_length=100)),
                ('WEIGHT', models.IntegerField()),
                ('BELT_LEVEL', models.IntegerField()),
                ('GENDER', models.BooleanField()),
                ('TEAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.club')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAT_NUMBER', models.IntegerField()),
                ('RESULT', models.BooleanField()),
                ('SCORE', models.IntegerField()),
                ('COMPETITOR1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor1', to='project.competitor')),
                ('COMPETITOR2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor2', to='project.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOURNAMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.competition')),
                ('MATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.match')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENTRANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.club')),
                ('TOURNAMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.competition')),
            ],
        ),
    ]
