# Generated by Django 5.1.3 on 2024-11-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracketmatch',
            old_name='TOURNAMENT',
            new_name='COMPETITION',
        ),
        migrations.RenameField(
            model_name='tournamententry',
            old_name='TOURNAMENT',
            new_name='COMPETITION',
        ),
    ]
