# Generated by Django 5.1.3 on 2024-11-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_tournament_bracketmatch_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='WEIGHT',
            field=models.FloatField(),
        ),
    ]
