# Generated by Django 5.1.3 on 2024-11-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_competitor_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='CLUB_NAME',
            new_name='NAME',
        ),
    ]
