# Generated by Django 5.1.3 on 2024-12-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_club_name_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='COMPETITION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.competition'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BracketMatch',
        ),
    ]
